version: "3.3"

services:
  backend:
    image: himanshuchauhan1/dock_backend:latest  
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - database
      - redis
    environment:
      DB_USER: invue
      DB_PASS: invue!
      DB_NAME: local_testing_db
      DB_HOST: postgres_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network

  frontend:
    image: himanshuchauhan1/dock_frontend:latest  
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: invue
      POSTGRES_PASSWORD: invue!
      POSTGRES_DB: local_testing_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
