version: "3.3"

services:
  backend:
    build: ./backend_service
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - database
      - redis  # Add Redis dependency
    environment:
      DB_USER: invue
      DB_PASS: invue!
      DB_NAME: local_testing_db
      DB_HOST: postgres_db
      DB_PORT: 5432
      REDIS_HOST: redis    # Redis container name (you'll use this in the backend to connect to Redis)
      REDIS_PORT: 6379     # Default Redis port
    networks:
      - app-network

  frontend:
    build: ./my-react-app
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: invue
      POSTGRES_PASSWORD: invue!
      POSTGRES_DB: local_testing_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest   # Use the official Redis image
    container_name: redis
    ports:
      - "6379:6379"       # Expose Redis default port
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:           # Define a custom network to connect all services
    driver: bridge

