name: Build Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important: fetch all tags

      - name: Set up Git
        run: |
          git config --global user.name "hchauhan0111"
          git config --global user.email "himanshu.chauhan@nagarro.com"

      - name: Determine build tag from Git tags
        id: build-count
        run: |
          latest_tag=$(git tag --list 'v1-build-*' | sed 's/v1-build-//' | sort -n | tail -1)
          echo "Latest build number: ${latest_tag:-0}"
          next_count=$((latest_tag + 1))
          tag="v1-build-$next_count"
          echo "BUILD_TAG=$tag" >> $GITHUB_ENV
          echo "Using tag: $tag"
          
      - name: Create and push new Git tag
        run: |
          git tag ${{ env.BUILD_TAG }}
          git push https://x-access-token:${{ secrets.TAGTOKEN }}@github.com/${{ github.repository }} ${{ env.BUILD_TAG }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build and push backend_service Docker image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/backend_service:${{ env.BUILD_TAG }} ./backend_service
          docker push ${{ secrets.DOCKERUSERNAME }}/backend_service:${{ env.BUILD_TAG }}

      - name: Build and push my-react-app Docker image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/my-react-app:${{ env.BUILD_TAG }} ./my-react-app
          docker push ${{ secrets.DOCKERUSERNAME }}/my-react-app:${{ env.BUILD_TAG }}
